alias vi='nvim'
alias vim='nvim'
alias vimdiff='nvim -d'
alias neo='neovide'
alias code.='code .'
alias b="bundle exec"
alias ls='ls -G'
alias dir='ls -G --format=vertical'
alias rgrep='rgrep --color'
alias grep='grep --color'
alias dc='docker-compose'
alias w='CLICOLOR_FORCE=1 watch --color -n 10'
alias docker_clean_images='docker rmi $(docker images -a --filter=dangling=true -q)'
alias docker_clean_ps='docker rm $(docker ps --filter=status=exited --filter=status=created -q)'
