#!/usr/bin/env bash

mv ~/.vimrc{,.bak}
ln -s `pwd`/.vimrc $HOME/.vimrc

mv ~/.gvimrc{,.bak}
ln -s `pwd`/.gvimrc $HOME/.gvimrc

mv ~/.bashrc{,.bak}
ln -s `pwd`/.bashrc $HOME/.bashrc

mv ~/.screenrc{,.bak}
ln -s `pwd`/.screenrc $HOME/.screenrc

mv ~/.tmux.conf{,.bak}
ln -s `pwd`/.tmux.conf $HOME/.tmux.conf

mv ~/.projects{,.bak}
ln -s `pwd`/.projects $HOME/.projects

mv ~/.ackrc{,.bak}
ln -s `pwd`/.ackrc $HOME/.ackrc

mv ~/.gemrc{,.bak}
ln -s `pwd`/.gemrc $HOME/.gemrc

mv ~/.irbrc{,.bak}
ln -s `pwd`/.irbrc $HOME/.irbrc
