#!/usr/bin/env bash

mv ~/.vimrc ~/.vimrc.bax
ln -s `pwd`/.vimrc /home/$USER/.vimrc
mv ~/.gvimrc ~/.gvimrc.bak
ln -s `pwd`/.gvimrc /home/$USER/.gvimrc
mv ~/.bashrc ~/.bashrc.bak
ln -s `pwd`/.bashrc /home/$USER/.bashrc
mv ~/.screenrc ~/.screenrc.bak
ln -s `pwd`/.screenrc /home/$USER/.screenrc
